default: &default
  adapter: <%= ENV['DATABASE_ADAPTER']||'postgresql' %>
  encoding: <%= ENV['DATABASE_ENCODE']||'UTF-8' %>
  pool: <%= ENV['DATABASE_POOL'] || '5' %>
  timeout: <%= ENV['DATABASE_TIMEOUT'] || '5000' %>

test: <%= ENV['DATABASE_URL']%>
development: <%= ENV['DATABASE_URL']%>
production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL']%>