default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: carolina
  password: 
  timeout: 5000

development:
  <<: *default
  database: poketrader_dev
test:
  <<: *default
  database: poketrader_test

production:
  <<: *default
  database: poketrader  